import com.example.currencyconverter.R

enum class Currency(
    val resourceId: Int,
    val symbol: String,
    val fullName: String
) {
    USD(R.drawable.usd, "\u0024", "US Dollar"),
    GBP(R.drawable.gbp, "\u00A3", "British Pound Sterling"),
    EUR(R.drawable.eur, "\u20AC", "Euro"),
    AUD(R.drawable.aud, "\u0024", "Australian Dollar"),
    BGN(R.drawable.bgn, "lv", "Bulgarian Lev"),
    BRL(R.drawable.brl, "\u0052\u0024", "Brazilian Real"),
    CAD(R.drawable.cad, "\u0024", "Canadian Dollar"),
    CHF(R.drawable.chf, "Fr", "Swiss Franc"),
    CNY(R.drawable.cny, "\u00A5", "Chinese Yuan"),
    CZK(R.drawable.czk, "Kč", "Czech Koruna"),
    DKK(R.drawable.dkk, "kr", "Danish Krone"),
    HKD(R.drawable.hkd, "\u0024", "Hong Kong Dollar"),
    HRK(R.drawable.hrk, "kn", "Croatian Kuna"),
    HUF(R.drawable.huf, "Ft", "Hungarian Forint"),
    IDR(R.drawable.idr, "Rp", "Indonesian Rupiah"),
    ILS(R.drawable.ils, "\u20AA", "Israeli New Shekel"),
    INR(R.drawable.inr, "\u20B9", "Indian Rupee"),
    ISK(R.drawable.isk, "kr", "Icelandic Krona"),
    JPY(R.drawable.jpy, "\u00A5", "Japanese Yen"),
    KRW(R.drawable.krw, "\u20A9", "South Korean Won"),
    MXN(R.drawable.mxn, "\u0024", "Mexican Peso"),
    MYR(R.drawable.myr, "RM", "Malaysian Ringgit"),
    NOK(R.drawable.nok, "kr", "Norwegian Krone"),
    NZD(R.drawable.nzd, "\u0024", "New Zealand Dollar"),
    PHP(R.drawable.php, "\u20B1", "Philippine Peso"),
    PLN(R.drawable.pln, "zł", "Polish Zloty"),
    RON(R.drawable.ron, "lei", "Romanian Leu"),
    RUB(R.drawable.rus, "\u20BD", "Rubles"),
    SEK(R.drawable.sek, "kr", "Swedish Krona"),
    SGD(R.drawable.sgd, "\u0024", "Singapore Dollar"),
    THB(R.drawable.thb, "\u0E3F", "Thai Baht"),
    TRY(R.drawable.resource_try, "\u20BA", "Turkish Lira"),
    ZAR(R.drawable.zar, "R", "South African Rand");
}